# Site settings
title: sociologiavirtuale
email: monaco.federico@gmail.com
description: SV
baseurl: "sociologiavirtuale.github.io" # the subpath of your site, e.g. /blog/
url: "sociologiavirtuale.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: https://github.com/sociologiavirtuale

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
